upd: --artifacts option added
changes related to the addition of -a|--artifacts option.

Signed-off-by: Thiago Canozzo Lahr <tclahr@br.ibm.com>

diff --git a/uac b/uac
--- a/uac
+++ b/uac
@@ -58,6 +58,8 @@ export PATH
 . "${UAC_DIR}/lib/is_element_in_list.sh"
 . "${UAC_DIR}/lib/is_integer.sh"
 . "${UAC_DIR}/lib/is_running_with_root_privileges.sh"
+. "${UAC_DIR}/lib/list_artifacts.sh"
+. "${UAC_DIR}/lib/list_profiles.sh"
 . "${UAC_DIR}/lib/load_config_file.sh"
 . "${UAC_DIR}/lib/log_message.sh"
 . "${UAC_DIR}/lib/lrstrip.sh"
@@ -77,7 +79,7 @@ export PATH
 . "${UAC_DIR}/lib/validate_profile_file.sh"
 
 # global vars
-UAC_VERSION="2.0.0-rc3"
+UAC_VERSION="2.0.0-rc4"
 MOUNT_POINT="/"
 OPERATING_SYSTEM=""
 SYSTEM_ARCH=""
@@ -89,7 +91,8 @@ END_DATE_DAYS=""
 END_DATE_EPOCH=""
 
 # local vars
-ua_profile_name=""
+ua_artifacts=""
+ua_profile=""
 ua_destination_dir=""
 ua_run_as_non_root=false
 ua_temp_dir=""
@@ -113,7 +116,40 @@ ua_command_line="$0 $@"
 
 # parse command line arguments
 while [ "${1:-}" != "" ]; do
-  case "${1}" in    
+  case "${1}" in
+    # optional arguments
+    "-h"|"--help")
+      usage
+      exit 1
+      ;;
+    "-V"|"--version")
+      printf %b "UAC (Unix-like Artifacts Collector) v${UAC_VERSION}\n"
+      exit 0
+      ;;
+    "--debug")
+      ua_debug_mode=true
+      ;;
+    # profiling arguments
+    "-p"|"--profile")
+      if [ -n "${2}" ]; then
+        ua_profile="${2}"
+        shift
+      else
+        printf %b "uac: option '${1}' requires an argument.\n\
+Try 'uac --help' for more information.\n" >&2
+        exit 1
+      fi
+      ;;
+    "-a"|"--artifacts")
+      if [ -n "${2}" ]; then
+        ua_artifacts="${2}"
+        shift
+      else
+        printf %b "uac: option '${1}' requires an argument.\n\
+Try 'uac --help' for more information.\n" >&2
+        exit 1
+      fi
+      ;;
     # collection arguments
     "-m"|"--mount-point")
       if [ -n "${2}" ]; then
@@ -276,18 +312,6 @@ Try 'uac --help' for more information.\n" >&2
         exit 1
       fi
       ;;
-    # optional arguments
-    "-h"|"--help")
-      usage
-      exit 1
-      ;;
-    "-V"|"--version")
-      printf %b "UAC (Unix-like Artifacts Collector) v${UAC_VERSION}\n"
-      exit 0
-      ;;
-    "--debug")
-      ua_debug_mode=true
-      ;;
     # invalid arguments
     -*)
       printf %b "uac: invalid option '${1}'\n\
@@ -296,9 +320,7 @@ Try 'uac --help' for more information.\n" >&2
       ;;
     # positional arguments
     *)
-      if [ -z "${ua_profile_name}" ]; then
-        ua_profile_name=`echo "${1}" | sed -e 's:/::g'`
-      elif [ -z "${ua_destination_dir}" ]; then
+      if [ -z "${ua_destination_dir}" ]; then
         ua_destination_dir="${1}"
       else
         printf %b "uac: invalid option '${1}'\n\
@@ -313,29 +335,67 @@ done
 # treat unset variables as an error when substituting
 set -u
 
-# exit if neither profile nor destination directory is set
-if [ -z "${ua_profile_name}" ] || [ -z "${ua_destination_dir}" ]; then
+# print available profiles
+if [ -n "${ua_profile}" ] && [ "${ua_profile}" = "list" ]; then
+  list_profiles
+  exit 1
+fi
+
+# print available artifacts
+if [ -n "${ua_artifacts}" ] && [ "${ua_artifacts}" = "list" ]; then
+  list_artifacts
+  exit 1
+fi
+
+# exit if a profile name and artifacts have been provided
+if [ -n "${ua_profile}" ] && [ -n "${ua_artifacts}" ]; then
+  printf %b "uac: invalid option '--artifacts'. \
+A collection profile has already been provided.\n"
+  exit 1
+fi
+
+# exit if profile and artifacts, or destination dir is empty
+if { [ -z "${ua_profile}" ] && [ -z "${ua_artifacts}" ]; } \
+  || [ -z "${ua_destination_dir}" ] ; then
   usage
   exit 1
 fi
 
-# get proper profile file based on the profile name
-ua_profile_file=""
-for ua_file in "${UAC_DIR}"/profiles/*.yaml; do
-  if grep -q -E "name: +${ua_profile_name} *$" <"${ua_file}"; then
-    ua_profile_file="${ua_file}"
-    break
+# profile name provided
+if [ -n "${ua_profile}" ]; then
+  # get proper profile file based on the profile name
+  ua_profile_file=""
+  for ua_file in "${UAC_DIR}"/profiles/*.yaml; do
+    if grep -q -E "name: +${ua_profile} *$" <"${ua_file}"; then
+      ua_profile_file="${ua_file}"
+      break
+    fi
+  done
+
+  # exit if profile not found
+  if [ -z "${ua_profile_file}" ]; then
+    printf %b "uac: profile not found '${ua_profile}'\n"
+    exit 1
   fi
-done
 
-# exit if profile not found
-if [ -z "${ua_profile_file}" ]; then
-  printf %b "uac: profile not found '${ua_profile_name}'\n"
-  exit 1
+  # check if profile file is valid
+  validate_profile_file "${ua_profile_file}" || exit 1
+else
+  # artifacts list provided
+  OIFS="${IFS}"
+  IFS=","
+  for ua_artifact_file in ${ua_artifacts}; do
+    ua_artifact_file=`echo "${ua_artifact_file}" | sed -e 's:^!::g' -e 's:\.\.::g'`
+    find "${UAC_DIR}"/artifacts/${ua_artifact_file} -name "*.yaml" \
+      -type f -print >/dev/null 2>/dev/null
+    if [ "$?" -gt 0 ]; then
+      printf %b "uac: artifact file not found \
+'"${UAC_DIR}"/artifacts/${ua_artifact_file}'\n" >&2
+      exit 1
+    fi
+  done
+  IFS="${OIFS}"
 fi
-
-# check if profile file is valid
-validate_profile_file "${ua_profile_file}" || exit 1
 
 # check if destination directory exists
 if [ ! -d "${ua_destination_dir}" ]; then
@@ -487,7 +547,6 @@ printf %b "---------------------------------------------------------------------
 # start uac.log file
 log_message INFO "UAC (Unix-like Artifacts Collector) v${UAC_VERSION}"
 log_message INFO "Command line: ${ua_command_line}"
-log_message INFO "Profile file: ${ua_profile_file}"
 log_message INFO "Operating system: ${OPERATING_SYSTEM}"
 log_message INFO "System architecture: ${SYSTEM_ARCH}"
 log_message INFO "Hostname: ${ua_hostname}"
@@ -535,8 +594,21 @@ log_message INFO "'statx' tool available: ${STATX_TOOL_AVAILABLE}"
 
 log_message INFO "PATH: ${PATH}"
 
+# create a temporary profile file based on the artifacts provided via command
+# line
+if [ -n "${ua_artifacts}" ]; then
+  printf %b "artifacts:\n" >>"${TEMP_DATA_DIR}/.profile.yaml"
+  OIFS="${IFS}"
+  IFS=","
+  for ua_artifact_file in ${ua_artifacts}; do
+    printf %b "  - ${ua_artifact_file}\n" >>"${TEMP_DATA_DIR}/.profile.yaml"
+  done
+  IFS="${OIFS}"
+  ua_profile_file="${TEMP_DATA_DIR}/.profile.yaml"
+fi
+
 # parse profile file
-log_message INFO "Parsing profile file"
+log_message INFO "Parsing profile file '${ua_profile_file}'"
 parse_profile_file "${ua_profile_file}" || exit 1
 
 # add UAC_DIR abd TEMP_DATA_DIR to GLOBAL_EXCLUDE_PATH_PATTERN
